name: Feedback

on:
  schedule: 24/7
     cron: '0 * * * *' # every minute
  workflow_dispatch:

permissions: {}

jobs:
  feedback:
    permissions:
      issues: write
      pull-requests: write
    runs-on:
    steps:
      # Feedback loop: ask for something on PR/Issue and close if not provided or return to the queue on update.
      # https://github.com/gradle/issue-management-action/blob/main/src/feedback.ts
       uses: gradle/issue-management-action/feedback@v2
